package com.fusionquery.jdbc;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class FusionConnection implements Connection {

    private final FusionQueryClient client;
    private final String url;
    private final Properties info;
    private boolean closed = false;
    private boolean autoCommit = true;
    private boolean readOnly = true;

    private String deployWarning;

    public FusionConnection(FusionQueryClient client, String url, Properties info) {
        this.client = client;
        this.url = url;
        this.info = info;
        autoDeploy();
    }

    private void autoDeploy() {
        try {
            boolean isOcs = client.getBaseUrl().contains(".ocs.");
            FusionCatalogService catalog = new FusionCatalogService(
                    client.getBaseUrl(), client.getUsername(),
                    client.getPassword(), client.getTimeoutMs());

            if (isOcs) {
                catalog.setUseSoap(true);
                client.setUseSoap(true);
            }

            FusionCatalogService.DeployResult result = catalog.ensureDeployed();
            if (result.found && result.reportPath != null) {
                client.setReportPath(result.reportPath);
                if (result.wasInstalled) {
                    deployWarning = "Proxy report deployed to: " + result.reportPath;
                }
            } else if (result.error != null) {
                deployWarning = result.error;
            }
        } catch (Exception e) {
            deployWarning = "Auto-deploy failed: " + e.getMessage();
        }
    }

    FusionQueryClient getClient() { return client; }

    @Override
    public Statement createStatement() throws SQLException {
        checkClosed();
        return new FusionStatement(this);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return createStatement();
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        checkClosed();
        return new FusionPreparedStatement(this, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        checkClosed();
        return new FusionDatabaseMetaData(this);
    }

    @Override
    public void close() throws SQLException {
        closed = true;
    }

    @Override
    public boolean isClosed() { return closed; }

    @Override
    public void setAutoCommit(boolean autoCommit) { this.autoCommit = autoCommit; }

    @Override
    public boolean getAutoCommit() { return autoCommit; }

    @Override
    public void commit() {}

    @Override
    public void rollback() {}

    @Override
    public void setReadOnly(boolean readOnly) { this.readOnly = true; }

    @Override
    public boolean isReadOnly() { return true; }

    @Override
    public void setCatalog(String catalog) {}

    @Override
    public String getCatalog() { return "FUSION"; }

    @Override
    public void setTransactionIsolation(int level) {}

    @Override
    public int getTransactionIsolation() { return Connection.TRANSACTION_READ_COMMITTED; }

    @Override
    public SQLWarning getWarnings() {
        return deployWarning != null ? new SQLWarning(deployWarning) : null;
    }

    @Override
    public void clearWarnings() { deployWarning = null; }

    @Override
    public boolean isValid(int timeout) {
        if (closed) return false;
        try {
            QueryResult result = client.query("SELECT 1 FROM DUAL");
            return !result.hasError();
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public String getSchema() { return "FUSION"; }

    @Override
    public void setSchema(String schema) {}

    @Override
    public Map<String, Class<?>> getTypeMap() { return Map.of(); }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) {}

    @Override
    public int getHoldability() { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }

    @Override
    public void setHoldability(int holdability) {}

    @Override
    public Savepoint setSavepoint() throws SQLException { throw unsupported(); }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException { throw unsupported(); }

    @Override
    public void rollback(Savepoint savepoint) {}

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException { throw unsupported(); }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException { throw unsupported(); }

    @Override
    public CallableStatement prepareCall(String sql, int a, int b) throws SQLException { throw unsupported(); }

    @Override
    public CallableStatement prepareCall(String sql, int a, int b, int c) throws SQLException { throw unsupported(); }

    @Override
    public String nativeSQL(String sql) { return sql; }

    @Override
    public void setClientInfo(String name, String value) {}

    @Override
    public void setClientInfo(Properties properties) {}

    @Override
    public String getClientInfo(String name) { return null; }

    @Override
    public Properties getClientInfo() { return new Properties(); }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException { throw unsupported(); }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException { throw unsupported(); }

    @Override
    public Clob createClob() throws SQLException { throw unsupported(); }

    @Override
    public Blob createBlob() throws SQLException { throw unsupported(); }

    @Override
    public NClob createNClob() throws SQLException { throw unsupported(); }

    @Override
    public SQLXML createSQLXML() throws SQLException { throw unsupported(); }

    @Override
    public void abort(Executor executor) { closed = true; }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) {}

    @Override
    public int getNetworkTimeout() { return 0; }

    @Override
    public boolean isWrapperFor(Class<?> iface) { return false; }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException { throw unsupported(); }

    private void checkClosed() throws SQLException {
        if (closed) throw new SQLException("Connection is closed");
    }

    private static SQLException unsupported() {
        return new SQLFeatureNotSupportedException("Not supported by Fusion Query JDBC driver");
    }
}
