package com.fusionquery.jdbc;

import java.sql.*;

public class FusionStatement implements Statement {

    protected final FusionConnection connection;
    protected FusionResultSet currentResultSet;
    protected boolean closed = false;
    protected int maxRows = 0;
    protected int fetchSize = 1000;
    protected int queryTimeout = 0;

    public FusionStatement(FusionConnection connection) {
        this.connection = connection;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkClosed();
        sql = sql.trim();
        if (!sql.toUpperCase().startsWith("SELECT")) {
            throw new SQLException("Only SELECT statements are supported (read-only driver)");
        }

        QueryResult result = connection.getClient().query(sql, fetchSize, 0);
        if (result.hasError()) {
            String friendly = OracleErrorParser.parse(result.getError(), sql);
            throw new SQLException(friendly);
        }

        currentResultSet = new FusionResultSet(this, result, sql);
        return currentResultSet;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        executeQuery(sql);
        return true;
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return execute(sql);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        throw new SQLException("Only SELECT statements are supported (read-only driver)");
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return currentResultSet;
    }

    @Override
    public int getUpdateCount() { return -1; }

    @Override
    public boolean getMoreResults() { return false; }

    @Override
    public boolean getMoreResults(int current) { return false; }

    @Override
    public void close() throws SQLException {
        closed = true;
        if (currentResultSet != null) {
            currentResultSet.close();
        }
    }

    @Override
    public boolean isClosed() { return closed; }

    @Override
    public void setMaxRows(int max) { this.maxRows = max; }

    @Override
    public int getMaxRows() { return maxRows; }

    @Override
    public void setFetchSize(int rows) { this.fetchSize = rows > 0 ? rows : 1000; }

    @Override
    public int getFetchSize() { return fetchSize; }

    @Override
    public void setQueryTimeout(int seconds) { this.queryTimeout = seconds; }

    @Override
    public int getQueryTimeout() { return queryTimeout; }

    @Override
    public void setFetchDirection(int direction) {}

    @Override
    public int getFetchDirection() { return ResultSet.FETCH_FORWARD; }

    @Override
    public int getResultSetConcurrency() { return ResultSet.CONCUR_READ_ONLY; }

    @Override
    public int getResultSetType() { return ResultSet.TYPE_FORWARD_ONLY; }

    @Override
    public int getResultSetHoldability() { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }

    @Override
    public Connection getConnection() { return connection; }

    @Override
    public void cancel() {}

    @Override
    public SQLWarning getWarnings() { return null; }

    @Override
    public void clearWarnings() {}

    @Override
    public void setCursorName(String name) {}

    @Override
    public void setMaxFieldSize(int max) {}

    @Override
    public int getMaxFieldSize() { return 0; }

    @Override
    public void setEscapeProcessing(boolean enable) {}

    @Override
    public void addBatch(String sql) throws SQLException { throw unsupported(); }

    @Override
    public void clearBatch() {}

    @Override
    public int[] executeBatch() throws SQLException { throw unsupported(); }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return new FusionResultSet(this, new QueryResult(
                java.util.Collections.emptyList(), java.util.Collections.emptyList(),
                0, 0, 0, false, null), "");
    }

    @Override
    public void setPoolable(boolean poolable) {}

    @Override
    public boolean isPoolable() { return false; }

    @Override
    public void closeOnCompletion() {}

    @Override
    public boolean isCloseOnCompletion() { return false; }

    @Override
    public boolean isWrapperFor(Class<?> iface) { return false; }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException { throw unsupported(); }

    protected void checkClosed() throws SQLException {
        if (closed) throw new SQLException("Statement is closed");
    }

    private static SQLException unsupported() {
        return new SQLFeatureNotSupportedException("Not supported by Fusion Query JDBC driver");
    }
}
